### ISSUE TITLE
Add Android project files

### ISSUE THREAD

**Issue by madebr** [libsdl-org/SDL_helloworld#1]
After https://github.com/libsdl-org/SDL/issues/6315, it would be nice to add Android gradle project files.

I created https://github.com/madebr/sdlcross that uses (prefab) aar's, built by [build-scripts/android-prefab.sh](https://github.com/libsdl-org/SDL/blob/2e92e94ebb486ed351aae882656f71b1b0053ee2/build-scripts/android-prefab.sh).

**Comment by icculus** [comment]
The goal is to be as simple as possible without a ton of crud the user needs to weed through to get up and running. If we can get Android stuff in here without having it be totally gross, let's do it.

Part of me wishes this could just be something CMake spits out, but I know there's a bunch of steps to packaging an Android app beyond just compiling.

**Comment by madebr** [comment]
The goal is to allow people to simple open this project with android studio, and start developing. Right?
(That's my goal with the maven thing)

**Comment by icculus** [comment]
Go ahead and push anything you do to revision control; I trust you on this.  :)
